"""again

Revision ID: 307f37039441
Revises: 
Create Date: 2021-05-25 09:35:08.775210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307f37039441'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tribes', schema=None) as batch_op:
        batch_op.alter_column('challenge_wins',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tribes', schema=None) as batch_op:
        batch_op.alter_column('challenge_wins',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
